# encoder.yaml

encoder:

  block_configs:

    - cbad:
        filters: 32
        strides: 2

    - 64

    - cbad_stack:
        name: entry_flow_blocks
        seperable: true
        depth: 3
        output_stride: 2
        layers: [128,256,728]


    - cbad_stack:
        name: middle_flow
        nb_repeats: 16
        depth: 3
        filters: 728

    - cbad_stack:
        name: exit_flow_block
        output_stride: 2
        filters_list: [728,1024,1024]

    - cbad_stack:
        name: exit_flow_convs
        seperable: true
        residual: false
        layers: [1536,1536,2048]

    - aspp
