

xception:
  output_stride: 16
  entry_flow_prefilters_stack: [32,64]
  entry_flow_filters_stack: [128,256,728]
  middle_flow_filters: auto
  middle_flow_depth: 16
  exit_flow_filters_in: auto
  exit_flow_filters: 1024
  exit_flow_postfilters_stack: [1536,1536,2048]


small:
  output_stride: 4
  entry_flow_prefilters_stack: [32,64]
  entry_flow_filters_stack: [128]
  middle_flow_filters: auto
  middle_flow_depth: 4
  exit_flow_filters_in: auto
  exit_flow_filters: 256
  exit_flow_postfilters_stack: [512,512]